# -*- coding: utf-8 -*-
"""
Vision-to-Code Landing Page Builder - Pure Core API Backend
Strict separation of concerns. Pure REST endpoints for agents orchestration.
"""

import os
import json
import logging
from typing import List, Optional
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
import httpx
from bs4 import BeautifulSoup

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("LandingPageBuilderCore")

app = FastAPI(
    title="Vision-to-Code Core Agent API",
    description="Pure REST API backend executing the Multi-Agent vision-to-code pipeline.",
    version="1.0.0"
)

# Enable CORS for clean frontend/backend decoupling
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Adjust to your front-end domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration via environment variables
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = "gemini-3.5-flash"
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"


# Persistent In-Memory DOM State Manager
class LandingPageWorkspace:
    def __init__(self):
        self.current_html = ""

    def reset(self):
        self.current_html = ""

    def get_scaffold(self) -> str:
        return """<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;600;700;800&family=Montserrat:wght@300;400;700;900&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        body { font-family: 'Plus Jakarta Sans', sans-serif; }
    </style>
</head>
<body class="bg-[#FAF6F0] text-slate-800 min-h-screen">
    <div id="landing-builder-sections">
        <!-- SECTIONS_PLACEHOLDER -->
    </div>
    <script>
        lucide.createIcons();
    </script>
</body>
</html>"""

workspace = LandingPageWorkspace()

# --- SCHEMAS (DATA CONTRACTS) ---

class AnalyzeVisionRequest(BaseModel):
    image_base64: str = Field(..., description="Base64 encoded slice string of the landing page section")
    brand_context: Optional[str] = Field("", description="Optional tone guidelines or brand requirements")

class ResolveAssetRequest(BaseModel):
    prompt: str = Field(..., description="AI generation optimized prompt text in English")
    aspect_ratio: str = Field("1:1", description="Target aspect ratio dimension rules")

class GenerateSectionRequest(BaseModel):
    analysis_specs: dict = Field(..., description="The UI token specifications parsed by the Vision Agent")
    resolved_assets: dict = Field(..., description="Mapped dictionary connecting image IDs to their public safe links")

class CommitMergeRequest(BaseModel):
    section_html: str = Field(..., description="Raw component semantic HTML slice generated by the Code Agent")


# --- CORE AGENTS SERVICE PIPELINE ---

async def request_gemini_engine(endpoint: str, payload: dict) -> dict:
    """Helper connection pipeline to interface securely with the Gemini Engine API."""
    url = f"{GEMINI_API_URL}/{endpoint}?key={GEMINI_API_KEY}"
    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(url, json=payload, timeout=60.0)
            if response.status_code == 200:
                return response.json()
            raise HTTPException(
                status_code=response.status_code, 
                detail=f"Gemini Engine execution error: {response.text}"
            )
        except Exception as e:
            logger.error(f"Network abstraction fault connecting to Gemini API: {str(e)}")
            raise HTTPException(status_code=500, detail=f"AI Engine link failure: {str(e)}")


# --- REST API CONTROLLERS ---

@app.get("/", include_in_schema=False)
async def serve_frontend_ui():
    """Serves the frontend index.html from disk, keeping Python cleanly separated from HTML markup."""
    if os.path.exists("index.html"):
        return FileResponse("index.html")
    return HTMLResponse(
        content="""
        <div style="font-family: sans-serif; padding: 40px; text-align: center;">
            <h2 style="color: #4f46e5;">Backend Running Successfully!</h2>
            <p style="color: #4b5563;">Please ensure that you save the generated <b>index.html</b> file in the same directory as <b>app.py</b>.</p>
        </div>
        """,
        status_code=404
    )


@app.post("/api/agents/vision", summary="Agent 1: Multimodal Vision UI/UX Analyzer")
async def agent_vision_analysis(request: AnalyzeVisionRequest):
    """Deconstructs screenshot slices into granular styling tokens, extracted layout and copy schemas."""
    if "," in request.image_base64:
        request.image_base64 = request.image_base64.split(",")[1]

    system_instruction = (
        "Deconstruct the landing page section screenshot into structural tokens. Extract the type of layout, "
        "exact hexadecimal color values, font typography profiles, all contained copy strings, and asset requirements. "
        "For image requirements, write complex photographic prompts in English optimized for an image generation agent."
    )
    
    user_prompt = f"Analyze this user interface block. Additional user branding rules: {request.brand_context}"

    response_schema = {
        "type": "OBJECT",
        "properties": {
            "section_type": { "type": "STRING", "description": "hero, cta, features, pricing, faq, or testimonials" },
            "color_palette": {
                "type": "OBJECT",
                "properties": {
                    "bg": { "type": "STRING" },
                    "text_primary": { "type": "STRING" },
                    "accents": { "type": "ARRAY", "items": { "type": "STRING" } }
                },
                "required": ["bg", "text_primary", "accents"]
            },
            "typography": {
                "type": "OBJECT",
                "properties": {
                    "style": { "type": "STRING", "description": "serif, sans, display" },
                    "font_family": { "type": "STRING", "description": "Google Font name" }
                },
                "required": ["style", "font_family"]
            },
            "extracted_copy": {
                "type": "OBJECT",
                "properties": {
                    "title": { "type": "STRING" },
                    "subtitle": { "type": "STRING" },
                    "paragraphs": { "type": "ARRAY", "items": { "type": "STRING" } },
                    "cta_label": { "type": "STRING" }
                },
                "required": ["title", "subtitle", "paragraphs", "cta_label"]
            },
            "image_requirements": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "id": { "type": "STRING" },
                        "ai_generation_prompt": { "type": "STRING" },
                        "fallback_keywords": { "type": "ARRAY", "items": { "type": "STRING" } },
                        "aspect_ratio": { "type": "STRING" }
                    },
                    "required": ["id", "ai_generation_prompt", "fallback_keywords", "aspect_ratio"]
                }
            }
        },
        "required": ["section_type", "color_palette", "typography", "extracted_copy", "image_requirements"]
    }

    payload = {
        "contents": [{
            "parts": [
                {"text": user_prompt},
                {"inlineData": {"mimeType": "image/png", "data": request.image_base64}}
            ]
        }],
        "systemInstruction": {"parts": [{"text": system_instruction}]},
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    raw_response = await request_gemini_engine("gemini-2.5-flash-preview-09-2025:generateContent", payload)
    text_out = raw_response["candidates"][0]["content"]["parts"][0]["text"]
    return JSONResponse(content=json.loads(text_out))


@app.post("/api/agents/assets", summary="Agent 2: Autonomous Asset Generator (Imagen 4.0)")
async def agent_asset_resolution(request: ResolveAssetRequest):
    """Generates ultra-high resolution photography assets with Imagen 4.0 or triggers stock fallback mechanics."""
    payload = {
        "instances": [{"prompt": request.prompt}],
        "parameters": {
            "sampleCount": 1,
            "aspectRatio": request.aspect_ratio,
            "outputMimeType": "image/png"
        }
    }

    try:
        url = f"imagen-4.0-generate-001:predict?key={GEMINI_API_KEY}"
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{GEMINI_API_URL}/{url}", json=payload, timeout=60.0)
            if response.status_code == 200:
                img_data = response.json()["predictions"][0]["bytesBase64Encoded"]
                return {"secure_url": f"data:image/png;base64,{img_data}"}
            
            logger.warning("Imagen 4.0 bypassed or limited. Executing high-quality unsplash asset fallback match.")
            return {"secure_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=80"}
    except Exception as e:
        logger.error(f"Fallback asset route triggered due to: {str(e)}")
        return {"secure_url": "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&auto=format&fit=crop&q=80"}


@app.post("/api/agents/code", summary="Agent 3: Conversational Frontend Layout Engineer")
async def agent_code_generation(request: GenerateSectionRequest):
    """Translates processed design layout tokens and image maps into isolated, responsive semantic components."""
    system_instruction = (
        "You are a master frontend architect specialized in direct-response copy layout and conversion engineering. "
        "Translate user interface schemas into semantic, standalone clean blocks of HTML using Tailwind CSS classes, Google Fonts profiles, and Lucide icons. "
        "Strictly write all texts and vocabulary in an elegant, conversion-optimized Spanish language. "
        "Map the supplied resolved asset URLs straight to their corresponding <img> src attributes. "
        "Do not wrap your output in markdown code blocks like ```html. Return a valid structured JSON wrapper containing the html string."
    )

    user_prompt = (
        f"Generate the functional component using these specs: {json.dumps(request.analysis_specs)}. "
        f"Map these persistent resolved asset URLs directly to the template: {json.dumps(request.resolved_assets)}."
    )

    response_schema = {
        "type": "OBJECT",
        "properties": {
            "html_code": { "type": "STRING", "description": "Isolated component element HTML slice with styles" }
        },
        "required": ["html_code"]
    }

    payload = {
        "contents": [{"parts": [{"text": user_prompt}]}],
        "systemInstruction": {"parts": [{"text": system_instruction}]},
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    raw_response = await request_gemini_engine("gemini-2.5-pro:generateContent", payload)
    text_out = raw_response["candidates"][0]["content"]["parts"][0]["text"]
    return JSONResponse(content=json.loads(text_out))


@app.post("/api/compiler/merge", summary="Agent 4: Isolated DOM Tree Merger Engine")
async def compiler_dom_merge(request: CommitMergeRequest):
    """Surgically appends new code slices inside the live workspace DOM architecture tree safely using BeautifulSoup."""
    try:
        if not workspace.current_html:
            soup = BeautifulSoup(workspace.get_scaffold(), "html_parser")
        else:
            soup = BeautifulSoup(workspace.current_html, "html_parser")

        container = soup.find(id="landing-builder-sections")
        if not container:
            raise HTTPException(status_code=500, detail="The virtual workspace tree structure is missing its root grid anchor.")

        section_slice = BeautifulSoup(request.section_html, "html_parser")
        container.append(section_slice)

        # Append script to re-trigger Lucide icon evaluations on runtime additions
        if soup.body and not soup.find(id="lucide-reinit-script"):
            reinit_script = soup.new_tag("script", id="lucide-reinit-script")
            reinit_script.string = "lucide.createIcons();"
            soup.body.append(reinit_script)

        workspace.current_html = str(soup)
        return {"status": "success", "compiled_html": workspace.current_html}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Surgical tree compilation fault: {str(e)}")


@app.get("/api/compiler/workspace", summary="Fetch compiled output state")
async def compiler_get_workspace():
    """Queries the current overall compiled single-file pipeline code output."""
    return {"html": workspace.current_html}


@app.delete("/api/compiler/workspace", summary="Reset virtual tree project")
async def compiler_reset_workspace():
    """Wipes out the in-memory tree state to safely boot up a clean project canvas."""
    workspace.reset()
    return {"status": "workspace_canvas_cleared"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="127.0.0.1", port=8000, reload=True)